name: Validate the models in the repository
'on':
  push:
  pull_request:
  schedule:
  - cron: 0 10 * * 1
jobs:
  schema:
    name: Validate schema
    runs-on: ubuntu-latest
    container:
      image: cropsinsilico/yggdrasil-executable-dev:1d059a5af6dcf4b4dd88d1dca409aeb063b820bf
    steps:
    - uses: actions/checkout@v2
    - name: Validate the model YAMLs against the schema
      run: |
        conda info
        conda list
      # uses: cropsinsilico/yggdrasil-executable-dev:1d059a5af6dcf4b4dd88d1dca409aeb063b820bf
      # with:
      #   args: python utils/validate.py
      # run: python utils/validate.py
      # shell: bash -l {0}